services:
  - type: web
    name: airloom-sfo
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /status
    envVars:
      - key: PORT
        value: "8767"
      - key: ADSB_PRIMARY
        value: adsb.lol
      - key: OSKY_ID
        sync: false
      - key: OSKY_SECRET
        sync: false
      - key: AEROAPI_KEY
        sync: false
      - key: AEROAPI_DAILY_MAX_CALLS
        value: "48"
      - key: AEROAPI_DAILY_MAX_USD
        value: "0.50"
      - key: AEROAPI_MONTHLY_MAX_USD
        value: "5"
